version: 1

formatters:
    json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
        format: '%(asctime)s %(levelname)s %(name)s %(funcName)s %(lineno)d %(message)s'
    simple:
        format: '%(asctime)s - %(levelname)s - %(name)s - %(funcName)s - %(lineno)d - %(message)s'

handlers:
    file_handler: 
        class: logging.FileHandler
        level: DEBUG
        formatter: json
        filename: api_logfile.log
        encoding: utf8
    console: 
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
loggers:
    api_logger:
        level: DEBUG
        handlers: [file_handler, console]
