version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            git log
            git pull
            #last_tag=$(git describe --tags --abbrev=0)
            #docker build -t winorbit/orbita-api:$last_tag .
            #docker login -u winorbit -p X2GD6FKDTGmKG4V
            #docker push winorbit/orbita-api:$last_tag
