version: 2
jobs:
  build:
    environment:
            IMAGE_NAME: test:test 
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t test:test .
            docker login -u winorbit -p X2GD6FKDTGmKG4V
            docker build -t winorbit/orbita-api:newtag .
            docker push winorbit/orbita-api:newtag
