version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            git config --global user.email "winorbita@gmail.com"
            git config --global user.name "WinterOrbit"
            git remote set-url origin https://winorbit:$GITHUB_PASS@github.com/Winorbit/orbita_api.git

            LAST_COMMIT_TAIL=$(git rev-parse --short HEAD)
            CURRENT_BRUNCH_NAME=$(git rev-parse --abbrev-ref HEAD)

            git tag -a $LAST_COMMIT_TAIL -m "comment"
            git push origin $CURRENT_BRUNCH_NAME --follow-tags

            #DOCKERHUB
            docker build -t $DOCKERHUB_USER/orbita-api:$LAST_COMMIT_TAIL .
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker push winorbit/orbita-api:$LAST_COMMIT_TAIL
