version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            git config --global user.email "winorbita@gmail.com"
            git config --global user.name "WinterOrbit"
            git remote set-url origin https://winorbit:00z++19ftor@github.com/Winorbit/orbita_api.git


            last_commit_number=$(git rev-list --count HEAD)
            branch_name=$(git rev-parse --abbrev-ref HEAD)
            tag_name="$branch_name-V.$last_commit_number"

            git tag -a tag_name -m "comment"

            git push origin feature/add-circle-ci --follow-tags
            last_tag=$(git describe --tags --abbrev=0)
            docker build -t winorbit/orbita-api:[$tag_name] .
            docker login -u winorbit -p X2GD6FKDTGmKG4V
            docker push winorbit/orbita-api:$tag_name





# brunch_name+commit_number
# run tests
# if ok - get current data
# add tag
# Как лучше ставить метку? Скрипт с усовиями - мерж в мастер - дата и релиз, инкремент, инкремент с десятичным к кветке
# push tag to github

#2021.01.12--68
