version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            val=$(git describe --tags --abbrev=0)
            echo val
            echo $val
            echo ${val}
