version: 2
jobs:
  build:
    environment:
        LAST_TAG: test
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker login -u winorbit -p X2GD6FKDTGmKG4V
            docker build -t winorbit/orbita-api:$(git describe --exact-match --abbrev=0) .
            docker push winorbit/orbita-api:$(git describe --exact-match --abbrev=0)
